set(LOOM_ARCH x86 CACHE STRING "Target architecture")
set(LOOM_ENDIANNESS LITTLE CACHE STRING "Target architecture endianness")

set(CMAKE_SYSTEM_PROCESSOR i686)

set(CMAKE_NASM_COMPILER nasm)
set(CMAKE_ASM_NASM_FLAGS_INIT "-gdwarf")
set(CMAKE_ASM_NASM_OBJECT_FORMAT elf32)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)