set(CMAKE_SYSTEM_PROCESSOR i686)

set(CMAKE_NASM_COMPILER nasm)
set(CMAKE_ASM_NASM_FLAGS_INIT "-gdwarf")
set(CMAKE_ASM_NASM_OBJECT_FORMAT elf32)
set(CMAKE_C_COMPILER i686-elf-gcc)
set(CMAKE_OBJCOPY i686-elf-objcopy)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(LOOM_ENDIANNESS LITTLE CACHE STRING "Target architecture endianness")