target remote localhost:1234

set confirm off
set pagination off

layout src

set $moddir = "modules"
source gdb-mod.py

b loomMain

b loomModuleAdd
commands
    loom_gdb_module_load module
    c
end

c