set(LOOM_ARCH x86 CACHE STRING "Target architecture")
set(LOOM_ENDIANNESS LITTLE CACHE STRING "Target architecture endianness")

set(CMAKE_SYSTEM_PROCESSOR i686)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)